/**
 * Author:Josef Pavelec <jospavelec@gmail.com>
 */

CREATE TABLE "PERSON" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "USERNAME" VARCHAR(64) NOT NULL,
    "ISADMIN" BOOLEAN NOT NULL
);

CREATE TABLE "EVALUATION" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "PERSONID" BIGINT NOT NULL,
    "ANSWERID" BIGINT NOT NULL,
    "RATING" VARCHAR(10) NOT NULL,
    "ELAPSEDTIME" INTEGER NOT NULL
);

CREATE TABLE "ANSWER" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "SUBPACKID" BIGINT NOT NULL,
    "ANSWERVALUE" VARCHAR(100) NOT NULL,
    "ISNOISE" BOOLEAN NOT NULL
);

CREATE TABLE "ASSIGNEDPERSON" (
    "PERSONID" BIGINT NOT NULL,
    "SUBPACKID" BIGINT NOT NULL
);

CREATE TABLE "SUBPACK" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "PACKID" BIGINT NOT NULL,
    "NAME" VARCHAR(30) NOT NULL
);

CREATE TABLE "PACK" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "QUESTION" VARCHAR(250) NOT NULL,
    "NAME" VARCHAR(30) NOT NULL,
    "REPEAT" SMALLINT NOT NULL,
    "NOISE" SMALLINT NOT NULL
);

CREATE TABLE "REPEATANSWER" (
    "SUBPACKID" BIGINT NOT NULL,
    "ANSWERID" BIGINT NOT NULL
);