/**
 * Author:Josef Pavelec <jospavelec@gmail.com>
 */

CREATE TABLE "PERSON" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "USERNAME" VARCHAR(64) NOT NULL
);

CREATE TABLE "PACK" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "QUESTION" VARCHAR(250) NOT NULL,
    "NAME" VARCHAR(30) NOT NULL,
    /* TODO change repeat and noise types to DECIMAL(3,2) e.g. 3.28, 14.09 or 100 */
    "REPEAT" SMALLINT NOT NULL,
    "NOISE" SMALLINT NOT NULL
);

CREATE TABLE "SUBPACK" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "PACKID" BIGINT NOT NULL REFERENCES PACK(ID),
    "NAME" VARCHAR(30) NOT NULL
);

CREATE TABLE "ANSWER" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "SUBPACKID" BIGINT NOT NULL REFERENCES SUBPACK(ID),
    "ANSWERVALUE" VARCHAR(100) NOT NULL,
    "ISNOISE" BOOLEAN NOT NULL
);

CREATE TABLE "EVALUATION" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "PERSONID" BIGINT NOT NULL REFERENCES PERSON(ID),
    "ANSWERID" BIGINT NOT NULL REFERENCES ANSWER(ID),
    "RATING" VARCHAR(10) NOT NULL,
    "ELAPSEDTIME" INTEGER NOT NULL
);

CREATE TABLE "ASSIGNEDPERSON" (
    "PERSONID" BIGINT NOT NULL REFERENCES PERSON(ID),
    "SUBPACKID" BIGINT NOT NULL REFERENCES SUBPACK(ID)
);

CREATE TABLE "REPEATANSWER" (
    "SUBPACKID" BIGINT NOT NULL REFERENCES SUBPACK(ID),
    "ANSWERID" BIGINT NOT NULL REFERENCES ANSWER(ID)
);