/**
 * Author:Josef Pavelec <jospavelec@gmail.com>
 */

CREATE TABLE "PERSON" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "USERNAME" VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE "PACK" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "QUESTION" VARCHAR(250) NOT NULL,
    "NAME" VARCHAR(60) NOT NULL,
    "REPEAT" REAL NOT NULL,
    "NOISE" REAL NOT NULL
);

CREATE TABLE "SUBPACK" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "PACKID" BIGINT NOT NULL REFERENCES PACK(ID) ON DELETE CASCADE,
    "NAME" VARCHAR(60) NOT NULL
);

CREATE TABLE "ANSWER" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "SUBPACKID" BIGINT NOT NULL REFERENCES SUBPACK(ID) ON DELETE CASCADE,
    "ANSWERVALUE" VARCHAR(100) NOT NULL,
    "ISNOISE" BOOLEAN NOT NULL
);

CREATE TABLE "EVALUATION" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "PERSONID" BIGINT NOT NULL REFERENCES PERSON(ID) ON DELETE CASCADE,
    "ANSWERID" BIGINT NOT NULL REFERENCES ANSWER(ID) ON DELETE CASCADE,
    "RATING" VARCHAR(10) NOT NULL,
    "ELAPSEDTIME" INTEGER NOT NULL
);
/* TO DO add startday and endday */
CREATE TABLE "ASSIGNEDPERSON" (
    "PERSONID" BIGINT NOT NULL REFERENCES PERSON(ID) ON DELETE CASCADE,
    "SUBPACKID" BIGINT NOT NULL REFERENCES SUBPACK(ID) ON DELETE CASCADE
);

CREATE TABLE "REPEATANSWER" (
    "SUBPACKID" BIGINT NOT NULL REFERENCES SUBPACK(ID) ON DELETE CASCADE,
    "ANSWERID" BIGINT NOT NULL REFERENCES ANSWER(ID) ON DELETE CASCADE
);