/**
 * Author:Ondrej Velisek <ondrejvelisek@gmail.com>
 */
DROP TABLE "REPEATANSWER";

DROP TABLE "PACK";

DROP TABLE "SUBPACK";

DROP TABLE "ASSIGNEDPERSON";

DROP TABLE "ANSWER";

DROP TABLE "EVALUATION";

DROP TABLE "PERSON";