/**
 * Author:  Josef Pavelec <jospavelec@gmail.com>
 */
/*
INSERT INTO "PERSON" ("USERNAME", "ISADMIN") VALUES ('Jan Novak', false)

INSERT INTO "PERSON" ("USERNAME", "ISADMIN") VALUES ('Felix Slovacek', false)

INSERT INTO "PERSON" ("USERNAME", "ISADMIN") VALUES ('Gregor Pravy', true)

INSERT INTO "PACK" ("QUESTION", "NAME", "REPEAT", "NOISE") VALUES ('Je to zvire?', 'Animal', 3, 3)

INSERT INTO "PACK" ("QUESTION", "NAME", "REPEAT", "NOISE") VALUES ('Je to osoba?', 'Person', 2, 4)

INSERT INTO "PACK" ("QUESTION", "NAME", "REPEAT", "NOISE") VALUES ('Je to profese?', 'Job', 4, 2)

INSERT INTO "PACK" ("QUESTION", "NAME", "REPEAT", "NOISE") VALUES ('Je to film?', 'Movie', 3, 4)

INSERT INTO "SUBPACK" ("PACKID", "NAME") VALUES (1, 'A_01')

INSERT INTO "SUBPACK" ("PACKID", "NAME") VALUES (1, 'A_02')

INSERT INTO "SUBPACK" ("PACKID", "NAME") VALUES (2, 'A_03')

INSERT INTO "ANSWER" ("SUBPACKID", "ANSWERVALUE", "ISNOISE") VALUES (1, 'Pes', false)

INSERT INTO "ANSWER" ("SUBPACKID", "ANSWERVALUE", "ISNOISE") VALUES (1, 'Kocka', false)

INSERT INTO "ANSWER" ("SUBPACKID", "ANSWERVALUE", "ISNOISE") VALUES (1, 'adf22ad0', true)

INSERT INTO "EVALUATION" ("PERSONID", "ANSWERID", "RATING", "ELAPSEDTIME") VALUES (1, 1, '+', 2000)

INSERT INTO "EVALUATION" ("PERSONID", "ANSWERID", "RATING", "ELAPSEDTIME") VALUES (1, 2, '+', 1000)

INSERT INTO "EVALUATION" ("PERSONID", "ANSWERID", "RATING", "ELAPSEDTIME") VALUES (1, 3, '-', 3000)
*/